"""
Frankie BLD-1 output contract, plus the S120/S121 Sol adapter.

This replaces the guessed p_up/size/regime/contradiction/evidence/sigma
schema. Those names were never Frankie's interface. They may survive as
internal model heads, but nothing crosses this seam except the canonical
fields below.

Two structural facts drove the rewrite.

ABSTENTION IS A COMPLETE RECORD, NOT AN ABSENCE.
    The adapter carries disposition: CALL | ABSTAIN. Frankie expects all
    twelve fields either way. So an abstention is not a truncated
    emission -- it is a fully-formed record with disposition=ABSTAIN,
    financial fields zeroed rather than null, empty play lists, and the
    reason written into state_defects_and_gaps_reported. A downstream
    consumer must never have to branch on missing keys.

REASONING IS FREE TEXT AND CANNOT BE IN THE DETERMINISM CONTRACT.
    Every other field is a projection of typed head outputs and is
    reproducible. reasoning is not. It is validated for type and
    presence, and excluded from the determinism digest, so that a
    reworded explanation cannot look like a changed decision. If
    reasoning is ever generated by a sampler, that sampler's seed and
    version belong in the stamp -- see reasoning_digest below.

THE TRUNK IS ADDITIVE.
    This contract is the projection target for new model output. It does
    not replace or disconnect Frankie's existing field population. The
    seam is one-directional: internal heads -> BLD-1. Nothing here reads
    back into Frankie's own state.
"""

from __future__ import annotations

import hashlib
import json
import math
from dataclasses import dataclass
from enum import Enum
from typing import Any, Mapping, Sequence

__all__ = [
    "CallerError",
    "Disposition",
    "BLDField",
    "BLD1_FIELDS",
    "BLD1_FIELD_NAMES",
    "BLDRecord",
    "ContractError",
    "FrankieProjector",
    "validate_bld1",
]

CONTRACT_ID = "BLD-1"
ADAPTER_ID = "S120/S121"

# Free text. Reproducible only up to its digest, so it is excluded from
# the determinism comparison. Everything else is a typed projection.
NON_DETERMINISTIC_FIELDS = frozenset({"reasoning"})


class Disposition(str, Enum):
    CALL = "CALL"
    ABSTAIN = "ABSTAIN"


class ContractError(Exception):
    def __init__(self, field: str, detail: str):
        self.field = field
        self.detail = detail
        super().__init__(f"{field}: {detail}")


class CallerError(Exception):
    """The caller supplied unusable context (bad date, empty specialist).

    Distinct from ContractError on purpose. A model that emits garbage
    abstains; a caller that passes an unparseable date has a bug, and
    silently abstaining would hide it. There is no valid BLD-1 record to
    emit in that case -- not even an ABSTAIN one, since date is required.
    """ 


class Kind(str, Enum):
    IDENTIFIER = "identifier"
    DATE = "date"
    USD = "usd"
    CURVE = "curve"
    TEXT = "text"
    STR_LIST = "str_list"
    UNIT = "unit"  # [0, 1]
    DISPOSITION = "disposition"


@dataclass(frozen=True, slots=True)
class BLDField:
    name: str
    kind: Kind
    zero_on_abstain: Any = None

    def validate(self, value: Any) -> Any:
        k = self.kind

        if k is Kind.DISPOSITION:
            if isinstance(value, Disposition):
                return value.value
            if value in (Disposition.CALL.value, Disposition.ABSTAIN.value):
                return value
            raise ContractError(self.name, f"{value!r} is not CALL or ABSTAIN")

        if k is Kind.IDENTIFIER:
            if not isinstance(value, str) or not value.strip():
                raise ContractError(self.name, "must be a non-empty string")
            return value

        if k is Kind.DATE:
            if not isinstance(value, str) or len(value) != 10 or value[4] != "-":
                raise ContractError(self.name, "must be an ISO date YYYY-MM-DD")
            y, m, d = value.split("-")
            if not (y.isdigit() and m.isdigit() and d.isdigit()):
                raise ContractError(self.name, "non-numeric date component")
            if not (1 <= int(m) <= 12 and 1 <= int(d) <= 31):
                raise ContractError(self.name, f"{value} is not a calendar date")
            return value

        if k is Kind.TEXT:
            if not isinstance(value, str):
                raise ContractError(self.name, f"expected str, got {type(value).__name__}")
            return value

        if k is Kind.STR_LIST:
            if not isinstance(value, (list, tuple)) or not all(
                isinstance(v, str) for v in value
            ):
                raise ContractError(self.name, "must be a list of strings")
            return list(value)

        if k is Kind.CURVE:
            if not isinstance(value, (list, tuple)) or not value:
                raise ContractError(self.name, "must be a non-empty sequence")
            out = []
            for i, v in enumerate(value):
                if isinstance(v, bool) or not isinstance(v, (int, float)):
                    raise ContractError(self.name, f"point {i} is not numeric")
                f = float(v)
                if not math.isfinite(f):
                    raise ContractError(self.name, f"point {i} is {f}")
                out.append(f)
            return out

        # USD and UNIT
        if isinstance(value, bool) or not isinstance(value, (int, float)):
            raise ContractError(self.name, f"expected number, got {type(value).__name__}")
        f = float(value)
        if not math.isfinite(f):
            raise ContractError(self.name, "NaN or infinite value is not a call")
        if k is Kind.UNIT and not (0.0 <= f <= 1.0):
            raise ContractError(self.name, f"{f} outside [0, 1]")
        return f


BLD1_FIELDS: tuple[BLDField, ...] = (
    BLDField("specialist", Kind.IDENTIFIER),
    BLDField("group", Kind.IDENTIFIER),
    BLDField("date", Kind.DATE),
    BLDField("guessed_net_usd", Kind.USD, zero_on_abstain=0.0),
    BLDField("overnight_gap_usd", Kind.USD, zero_on_abstain=0.0),
    BLDField("path_p50_curve", Kind.CURVE, zero_on_abstain=[0.0]),
    BLDField("reasoning", Kind.TEXT, zero_on_abstain=""),
    BLDField("plays_fired", Kind.STR_LIST, zero_on_abstain=[]),
    BLDField("plays_stood_down", Kind.STR_LIST, zero_on_abstain=[]),
    BLDField("confidence", Kind.UNIT, zero_on_abstain=0.0),
    BLDField("state_defects_and_gaps_reported", Kind.STR_LIST, zero_on_abstain=[]),
    BLDField("disposition", Kind.DISPOSITION),
)

BLD1_FIELD_NAMES = tuple(f.name for f in BLD1_FIELDS)


def validate_bld1(payload: Mapping[str, Any]) -> dict[str, Any]:
    """Total validation. Missing and extra fields are both violations."""
    specs = {f.name: f for f in BLD1_FIELDS}
    missing = [n for n in specs if n not in payload]
    if missing:
        raise ContractError("<record>", f"absent fields: {sorted(missing)}")
    extra = [n for n in payload if n not in specs]
    if extra:
        raise ContractError("<record>", f"fields outside BLD-1: {sorted(extra)}")
    return {n: specs[n].validate(payload[n]) for n in BLD1_FIELD_NAMES}


@dataclass(frozen=True, slots=True)
class BLDRecord:
    payload: Mapping[str, Any]
    packet_hash: str
    model_version: str
    calibrator_version: str
    contract_id: str = CONTRACT_ID
    adapter_id: str = ADAPTER_ID

    @property
    def disposition(self) -> str:
        return self.payload["disposition"]

    @property
    def abstained(self) -> bool:
        return self.disposition == Disposition.ABSTAIN.value

    def reasoning_digest(self) -> str:
        """Digest of the free-text field, so a reworded explanation is
        visible in the audit without polluting the determinism check."""
        return hashlib.sha256(
            self.payload.get("reasoning", "").encode("utf-8")
        ).hexdigest()[:16]

    def deterministic_payload(self) -> dict[str, Any]:
        return {
            k: v for k, v in self.payload.items() if k not in NON_DETERMINISTIC_FIELDS
        }

    def determinism_digest(self) -> str:
        """Two emissions from the same packet must match on this."""
        body = {
            "payload": self.deterministic_payload(),
            "packet_hash": self.packet_hash,
            "model_version": self.model_version,
            "calibrator_version": self.calibrator_version,
            "contract_id": self.contract_id,
            "adapter_id": self.adapter_id,
        }
        return hashlib.sha256(
            json.dumps(body, sort_keys=True, separators=(",", ":")).encode()
        ).hexdigest()

    def to_json(self) -> str:
        return json.dumps(
            {
                "payload": {k: self.payload[k] for k in BLD1_FIELD_NAMES},
                "stamp": {
                    "packet_hash": self.packet_hash,
                    "model_version": self.model_version,
                    "calibrator_version": self.calibrator_version,
                    "contract_id": self.contract_id,
                    "adapter_id": self.adapter_id,
                    "reasoning_digest": self.reasoning_digest(),
                    "determinism_digest": self.determinism_digest(),
                },
            },
            sort_keys=True,
            separators=(",", ":"),
        )


# --------------------------------------------------------------------------
# Projection
# --------------------------------------------------------------------------


class FrankieProjector:
    """Projects internal head outputs into BLD-1.

    The internal head names are deliberately NOT hardcoded here beyond
    the ones the projection consumes. Add a head, and it stays internal
    until you decide how it maps to a BLD-1 field. Silent passthrough of
    a new internal quantity into Frankie's contract is exactly the kind
    of seam erosion the adapter exists to prevent.
    """

    def __init__(
        self,
        specialist: str,
        group: str,
        confidence_floor: float = 0.55,
        calibrator_version: str = "identity/1",
    ):
        self.specialist = specialist
        self.group = group
        self.confidence_floor = confidence_floor
        self.calibrator_version = calibrator_version

    def _check_context(self, date: str) -> str:
        for f in BLD1_FIELDS:
            if f.name == "date":
                try:
                    return f.validate(date)
                except ContractError as exc:
                    raise CallerError(str(exc)) from None
        raise AssertionError("date field missing from BLD1_FIELDS")

    def abstain(
        self,
        date: str,
        reasons: Sequence[str],
        packet_hash: str,
        model_version: str,
        reasoning: str = "",
    ) -> BLDRecord:
        """A complete record. Zeroed, not null; empty lists, not absent."""
        date = self._check_context(date)
        payload: dict[str, Any] = {
            "specialist": self.specialist,
            "group": self.group,
            "date": date,
            "disposition": Disposition.ABSTAIN.value,
            "reasoning": reasoning,
            "state_defects_and_gaps_reported": list(reasons),
        }
        for f in BLD1_FIELDS:
            if f.name not in payload:
                payload[f.name] = (
                    list(f.zero_on_abstain)
                    if isinstance(f.zero_on_abstain, list)
                    else f.zero_on_abstain
                )
        return BLDRecord(
            payload=validate_bld1(payload),
            packet_hash=packet_hash,
            model_version=model_version,
            calibrator_version=self.calibrator_version,
        )

    def project(
        self,
        date: str,
        heads: Mapping[str, Any],
        packet_hash: str,
        model_version: str,
        packet_defects: Sequence[str] = (),
        reasoning: str = "",
        plays_fired: Sequence[str] = (),
        plays_stood_down: Sequence[str] = (),
    ) -> BLDRecord:
        """Never raises on bad head output -- returns an ABSTAIN record.

        Packet defects abstain before anything is projected: a degraded
        packet cannot produce a call, and the defect list is what
        state_defects_and_gaps_reported exists to carry.
        """
        date = self._check_context(date)
        if packet_defects:
            return self.abstain(
                date, list(packet_defects), packet_hash, model_version, reasoning
            )

        try:
            conf = float(heads["confidence"])
            payload = {
                "specialist": self.specialist,
                "group": self.group,
                "date": date,
                "guessed_net_usd": heads["guessed_net_usd"],
                "overnight_gap_usd": heads["overnight_gap_usd"],
                "path_p50_curve": heads["path_p50_curve"],
                "reasoning": reasoning,
                "plays_fired": list(plays_fired),
                "plays_stood_down": list(plays_stood_down),
                "confidence": conf,
                "state_defects_and_gaps_reported": [],
                "disposition": Disposition.CALL.value,
            }
            checked = validate_bld1(payload)
        except ContractError as exc:
            return self.abstain(
                date, [f"contract_violation: {exc}"], packet_hash, model_version, reasoning
            )
        except (KeyError, TypeError, ValueError) as exc:
            return self.abstain(
                date,
                [f"head_output_malformed: {type(exc).__name__}: {exc}"],
                packet_hash,
                model_version,
                reasoning,
            )

        if checked["confidence"] < self.confidence_floor:
            # Stand down every play that would have fired. An abstention
            # that leaves plays_fired populated is a contradiction the
            # downstream cannot resolve.
            rec = self.abstain(
                date,
                [f"confidence {checked['confidence']:.4f} < {self.confidence_floor}"],
                packet_hash,
                model_version,
                reasoning,
            )
            merged = dict(rec.payload)
            merged["plays_stood_down"] = sorted(
                set(merged["plays_stood_down"]) | set(plays_fired) | set(plays_stood_down)
            )
            return BLDRecord(
                payload=validate_bld1(merged),
                packet_hash=packet_hash,
                model_version=model_version,
                calibrator_version=self.calibrator_version,
            )

        return BLDRecord(
            payload=checked,
            packet_hash=packet_hash,
            model_version=model_version,
            calibrator_version=self.calibrator_version,
        )
