"""
Frankie BLD-1 output contract, plus the S120/S121 Sol adapter.

This replaces the guessed p_up/size/regime/contradiction/evidence/sigma
schema. Those names were never Frankie's interface. They may survive as
internal model heads, but nothing crosses this seam except the canonical
fields below.

Two structural facts drove the rewrite.

ABSTENTION IS A COMPLETE RECORD, NOT AN ABSENCE.
    The adapter carries disposition: CALL | ABSTAIN. Frankie expects all
    twelve fields either way. S121 makes disposition independent of the
    market forecast: a forecast-backed ABSTAIN preserves its net, gap and
    endogenous curve. The zero forecast is reserved for the safety fallback
    when malformed or unavailable inputs leave no usable forecast.

REASONING IS FREE TEXT AND CANNOT BE IN THE DETERMINISM CONTRACT.
    Every other field is a projection of typed head outputs and is
    reproducible. reasoning is not. It is validated for type and
    presence, and excluded from the determinism digest, so that a
    reworded explanation cannot look like a changed decision. If
    reasoning is ever generated by a sampler, that sampler's seed and
    version belong in the stamp -- see reasoning_digest below.

THE TRUNK IS ADDITIVE.
    This contract is the projection target for new model output. It does
    not replace or disconnect Frankie's existing field population. The
    seam is one-directional: internal heads -> BLD-1. Nothing here reads
    back into Frankie's own state.
"""

from __future__ import annotations

import hashlib
import json
import math
import re
from dataclasses import dataclass, field
from enum import Enum
from types import MappingProxyType
from typing import Any, Mapping, Sequence

__all__ = [
    "CallerError",
    "Disposition",
    "BLDField",
    "BLD1_FIELDS",
    "BLD1_FIELD_NAMES",
    "INTERNAL_HEAD_TO_BLD1",
    "InternalBLD1Heads",
    "BLDRecord",
    "ContractError",
    "FrankieProjector",
    "validate_bld1",
]

CONTRACT_ID = "BLD-1"
ADAPTER_ID = "S120/S121"

# Free text. Reproducible only up to its digest, so it is excluded from
# the determinism comparison. Everything else is a typed projection.
NON_DETERMINISTIC_FIELDS = frozenset({"reasoning"})


class Disposition(str, Enum):
    CALL = "CALL"
    ABSTAIN = "ABSTAIN"


class ContractError(Exception):
    def __init__(self, field: str, detail: str):
        self.field = field
        self.detail = detail
        super().__init__(f"{field}: {detail}")


class CallerError(Exception):
    """The caller supplied unusable context (bad date, empty specialist).

    Distinct from ContractError on purpose. A model that emits garbage
    abstains; a caller that passes an unparseable date has a bug, and
    silently abstaining would hide it. There is no valid BLD-1 record to
    emit in that case -- not even an ABSTAIN one, since date is required.
    """


class Kind(str, Enum):
    IDENTIFIER = "identifier"
    DATE = "date"
    USD = "usd"
    CURVE = "curve"
    TEXT = "text"
    STR_LIST = "str_list"
    CONFIDENCE = "confidence"
    DISPOSITION = "disposition"


@dataclass(frozen=True, slots=True)
class BLDField:
    name: str
    kind: Kind
    zero_on_abstain: Any = None

    def validate(self, value: Any) -> Any:
        k = self.kind

        if k is Kind.DISPOSITION:
            if isinstance(value, Disposition):
                return value.value
            if value in (Disposition.CALL.value, Disposition.ABSTAIN.value):
                return value
            raise ContractError(self.name, f"{value!r} is not CALL or ABSTAIN")

        if k is Kind.IDENTIFIER:
            if not isinstance(value, str) or not value.strip():
                raise ContractError(self.name, "must be a non-empty string")
            return value

        if k is Kind.DATE:
            if not isinstance(value, str):
                raise ContractError(self.name, "must be YYYYMMDD or YYYY-MM-DD")
            compact = value.replace("-", "")
            if len(compact) != 8:
                raise ContractError(self.name, "must be YYYYMMDD or YYYY-MM-DD")
            y, m, d = compact[:4], compact[4:6], compact[6:]
            if not (y.isdigit() and m.isdigit() and d.isdigit()):
                raise ContractError(self.name, "non-numeric date component")
            if not (1 <= int(m) <= 12 and 1 <= int(d) <= 31):
                raise ContractError(self.name, f"{value} is not a calendar date")
            return value

        if k is Kind.TEXT:
            if not isinstance(value, str):
                raise ContractError(self.name, f"expected str, got {type(value).__name__}")
            return value

        if k is Kind.STR_LIST:
            if not isinstance(value, (list, tuple)) or not all(
                isinstance(v, str) for v in value
            ):
                raise ContractError(self.name, "must be a list of strings")
            return list(value)

        if k is Kind.CURVE:
            if not isinstance(value, (list, tuple)) or len(value) < 2:
                raise ContractError(self.name, "must contain at least two [et_time, cumulative_usd] points")
            out = []
            for i, point in enumerate(value):
                if not isinstance(point, (list, tuple)) or len(point) != 2:
                    raise ContractError(
                        self.name,
                        f"point {i} must be [et_time, cumulative_usd]",
                    )
                time_value, cumulative = point
                _et_hour(time_value, self.name, terminal=i == len(value) - 1)
                if (
                    isinstance(cumulative, bool)
                    or not isinstance(cumulative, (int, float))
                    or not math.isfinite(float(cumulative))
                ):
                    raise ContractError(
                        self.name, f"point {i} cumulative value must be finite numeric"
                    )
                out.append([time_value, float(cumulative)])
            return out

        if k is Kind.CONFIDENCE:
            if not isinstance(value, str) or value.lower() not in {"low", "med", "high"}:
                raise ContractError(self.name, "must be low|med|high")
            return value.lower()

        # USD
        if isinstance(value, bool) or not isinstance(value, (int, float)):
            raise ContractError(self.name, f"expected number, got {type(value).__name__}")
        f = float(value)
        if not math.isfinite(f):
            raise ContractError(self.name, "NaN or infinite value is not a call")
        return f


_TIME_RE = re.compile(r"^(?P<h>\d{1,2}):(?P<m>\d{2})$")


def _et_hour(raw: Any, field_name: str, *, terminal: bool = False) -> float:
    if isinstance(raw, bool):
        raise ContractError(field_name, "curve ET time must be numeric hour or HH:MM")
    if isinstance(raw, (int, float)):
        hour = float(raw)
        if terminal and math.isfinite(hour) and hour == 24.0:
            return hour
    elif isinstance(raw, str):
        text = raw.strip()
        if terminal and text == "24:00":
            return 24.0
        match = _TIME_RE.match(text)
        if not match:
            raise ContractError(field_name, f"invalid ET time {raw!r}")
        hh, minute = int(match.group("h")), int(match.group("m"))
        if hh > 23 or minute > 59:
            raise ContractError(field_name, f"invalid ET time {raw!r}")
        hour = hh + minute / 60.0
    else:
        raise ContractError(field_name, "curve ET time must be numeric hour or HH:MM")
    if not math.isfinite(hour) or hour < 0 or hour >= 24:
        raise ContractError(field_name, f"curve ET time {raw!r} outside [0,24)")
    return hour


def _curve_positions(curve: Sequence[Sequence[Any]]) -> list[tuple[float, float]]:
    positions: list[tuple[float, float]] = []
    prior: float | None = None
    for index, (raw_time, cumulative) in enumerate(curve):
        terminal = index == len(curve) - 1
        hour = _et_hour(raw_time, "path_p50_curve", terminal=terminal)
        if terminal and hour == 24.0:
            position = 24.0
        else:
            position = hour - 20.0 if hour >= 20.0 else hour + 4.0
            if terminal and prior is not None and hour == 20.0 and position <= prior:
                position = 24.0
        if prior is not None and position <= prior:
            raise ContractError(
                "path_p50_curve", "timestamps must be strictly chronological"
            )
        prior = position
        positions.append((position, float(cumulative)))
    return positions


def _mechanically_linear(points: Sequence[tuple[float, float]]) -> bool:
    if len(points) <= 2:
        return False
    x0, y0 = points[0]
    x1, y1 = points[-1]
    if abs(x1 - x0) <= 1e-12:
        return False
    return all(
        abs(y - (y0 + (y1 - y0) * (x - x0) / (x1 - x0))) <= 1e-7
        for x, y in points[1:-1]
    )


BLD1_FIELDS: tuple[BLDField, ...] = (
    BLDField("specialist", Kind.IDENTIFIER),
    BLDField("group", Kind.IDENTIFIER),
    BLDField("date", Kind.DATE),
    BLDField("guessed_net_usd", Kind.USD, zero_on_abstain=0.0),
    BLDField("overnight_gap_usd", Kind.USD, zero_on_abstain=0.0),
    BLDField(
        "path_p50_curve",
        Kind.CURVE,
        zero_on_abstain=[[20.0, 0.0], [24.0, 0.0]],
    ),
    BLDField("reasoning", Kind.TEXT, zero_on_abstain=""),
    BLDField("plays_fired", Kind.STR_LIST, zero_on_abstain=[]),
    BLDField("plays_stood_down", Kind.STR_LIST, zero_on_abstain=[]),
    BLDField("confidence", Kind.CONFIDENCE, zero_on_abstain="low"),
    BLDField("state_defects_and_gaps_reported", Kind.STR_LIST, zero_on_abstain=[]),
    BLDField("disposition", Kind.DISPOSITION),
)

BLD1_FIELD_NAMES = tuple(f.name for f in BLD1_FIELDS)


# The source names describe the learned quantity, not its transport field.
# This is deliberately the complete public mapping: every other learned value
# remains internal until a destination and semantics are separately specified.
INTERNAL_HEAD_TO_BLD1: Mapping[str, str] = MappingProxyType(
    {
        "session_net_usd": "guessed_net_usd",
        "overnight_gap_usd": "overnight_gap_usd",
        "session_path_p50_curve": "path_p50_curve",
        "confidence_label": "confidence",
    }
)


@dataclass(frozen=True, slots=True)
class InternalBLD1Heads:
    """The only learned quantities authorized to cross the BLD-1 seam.

    ``session_net_usd`` is the full prior-close-to-close move and therefore
    includes the overnight gap. ``session_path_p50_curve`` is cumulative from
    the session open, so its terminal value must equal session net less gap.
    ``confidence_label`` is the already-resolved BLD-1 ``low|med|high`` label;
    scores, probabilities, and logits stay internal until a threshold policy is
    separately specified. ``internal_only`` is retained for training, grading,
    and diagnostics but is never considered for projection.
    """

    session_net_usd: Any
    overnight_gap_usd: Any
    session_path_p50_curve: Sequence[Any]
    confidence_label: Any
    internal_only: Mapping[str, Any] = field(default_factory=dict)

    def __post_init__(self) -> None:
        object.__setattr__(
            self,
            "internal_only",
            MappingProxyType(dict(self.internal_only)),
        )

    def bld1_projection(self) -> dict[str, Any]:
        source = {
            "session_net_usd": self.session_net_usd,
            "overnight_gap_usd": self.overnight_gap_usd,
            "session_path_p50_curve": self.session_path_p50_curve,
            "confidence_label": self.confidence_label,
        }
        return {
            destination: source[internal]
            for internal, destination in INTERNAL_HEAD_TO_BLD1.items()
        }


def validate_bld1(payload: Mapping[str, Any]) -> dict[str, Any]:
    """Total validation. Missing and extra fields are both violations."""
    specs = {f.name: f for f in BLD1_FIELDS}
    missing = [n for n in specs if n not in payload]
    if missing:
        raise ContractError("<record>", f"absent fields: {sorted(missing)}")
    extra = [n for n in payload if n not in specs]
    if extra:
        raise ContractError("<record>", f"fields outside BLD-1: {sorted(extra)}")
    checked = {n: specs[n].validate(payload[n]) for n in BLD1_FIELD_NAMES}
    if not checked["reasoning"].strip():
        raise ContractError("reasoning", "must be non-empty")
    points = _curve_positions(checked["path_p50_curve"])
    if abs(points[0][1]) > 1e-9:
        raise ContractError(
            "path_p50_curve", "first cumulative value must be zero from day open"
        )
    endpoint = checked["guessed_net_usd"] - checked["overnight_gap_usd"]
    if not math.isclose(points[-1][1], endpoint, rel_tol=0.0, abs_tol=1.0):
        raise ContractError(
            "path_p50_curve",
            f"endpoint {points[-1][1]} != guessed_net_usd - overnight_gap_usd ({endpoint})",
        )
    if abs(points[-1][1]) > 1e-9 and _mechanically_linear(points):
        raise ContractError(
            "path_p50_curve", "A-86 decorative exact endpoint interpolation rejected"
        )
    return checked


@dataclass(frozen=True, slots=True)
class BLDRecord:
    payload: Mapping[str, Any]
    packet_hash: str
    model_version: str
    calibrator_version: str
    contract_id: str = CONTRACT_ID
    adapter_id: str = ADAPTER_ID

    @property
    def disposition(self) -> str:
        return self.payload["disposition"]

    @property
    def abstained(self) -> bool:
        return self.disposition == Disposition.ABSTAIN.value

    def reasoning_digest(self) -> str:
        """Digest of the free-text field, so a reworded explanation is
        visible in the audit without polluting the determinism check."""
        return hashlib.sha256(
            self.payload.get("reasoning", "").encode("utf-8")
        ).hexdigest()[:16]

    def deterministic_payload(self) -> dict[str, Any]:
        return {
            k: v for k, v in self.payload.items() if k not in NON_DETERMINISTIC_FIELDS
        }

    def determinism_digest(self) -> str:
        """Two emissions from the same packet must match on this."""
        body = {
            "payload": self.deterministic_payload(),
            "packet_hash": self.packet_hash,
            "model_version": self.model_version,
            "calibrator_version": self.calibrator_version,
            "contract_id": self.contract_id,
            "adapter_id": self.adapter_id,
        }
        return hashlib.sha256(
            json.dumps(body, sort_keys=True, separators=(",", ":")).encode()
        ).hexdigest()

    def to_json(self) -> str:
        return json.dumps(
            {
                "payload": {k: self.payload[k] for k in BLD1_FIELD_NAMES},
                "stamp": {
                    "packet_hash": self.packet_hash,
                    "model_version": self.model_version,
                    "calibrator_version": self.calibrator_version,
                    "contract_id": self.contract_id,
                    "adapter_id": self.adapter_id,
                    "reasoning_digest": self.reasoning_digest(),
                    "determinism_digest": self.determinism_digest(),
                },
            },
            sort_keys=True,
            separators=(",", ":"),
        )


# --------------------------------------------------------------------------
# Projection
# --------------------------------------------------------------------------


class FrankieProjector:
    """Projects internal head outputs into BLD-1.

    The internal head names are deliberately NOT hardcoded here beyond
    the ones the projection consumes. Add a head, and it stays internal
    until you decide how it maps to a BLD-1 field. Silent passthrough of
    a new internal quantity into Frankie's contract is exactly the kind
    of seam erosion the adapter exists to prevent.
    """

    def __init__(
        self,
        specialist: str,
        group: str,
        confidence_floor: float | None = None,
        calibrator_version: str = "identity/1",
    ):
        if confidence_floor is not None:
            raise ValueError(
                "numeric confidence floors are not part of BLD-1; "
                "project an already-governed low|med|high label"
            )
        self.specialist = specialist
        self.group = group
        self.calibrator_version = calibrator_version

    def _check_context(self, date: str) -> str:
        for f in BLD1_FIELDS:
            if f.name == "date":
                try:
                    return f.validate(date)
                except ContractError as exc:
                    raise CallerError(str(exc)) from None
        raise AssertionError("date field missing from BLD1_FIELDS")

    def abstain(
        self,
        date: str,
        reasons: Sequence[str],
        packet_hash: str,
        model_version: str,
        reasoning: str = "",
    ) -> BLDRecord:
        """A complete safety abstention when no usable forecast exists."""
        date = self._check_context(date)
        safe_reasoning = reasoning.strip() or "; ".join(reasons) or "No call."
        payload: dict[str, Any] = {
            "specialist": self.specialist,
            "group": self.group,
            "date": date,
            "disposition": Disposition.ABSTAIN.value,
            "reasoning": safe_reasoning,
            "state_defects_and_gaps_reported": list(reasons),
        }
        for f in BLD1_FIELDS:
            if f.name not in payload:
                payload[f.name] = (
                    list(f.zero_on_abstain)
                    if isinstance(f.zero_on_abstain, list)
                    else f.zero_on_abstain
                )
        return BLDRecord(
            payload=validate_bld1(payload),
            packet_hash=packet_hash,
            model_version=model_version,
            calibrator_version=self.calibrator_version,
        )

    def project(
        self,
        date: str,
        heads: Mapping[str, Any],
        packet_hash: str,
        model_version: str,
        packet_defects: Sequence[str] = (),
        reasoning: str = "",
        plays_fired: Sequence[str] = (),
        plays_stood_down: Sequence[str] = (),
        disposition: Disposition | str = Disposition.CALL,
    ) -> BLDRecord:
        """Never raises on bad head output -- returns an ABSTAIN record.

        Packet defects abstain before anything is projected: a degraded
        packet cannot produce a call, and the defect list is what
        state_defects_and_gaps_reported exists to carry.
        """
        date = self._check_context(date)
        if packet_defects:
            return self.abstain(
                date, list(packet_defects), packet_hash, model_version, reasoning
            )

        try:
            payload = {
                "specialist": self.specialist,
                "group": self.group,
                "date": date,
                "guessed_net_usd": heads["guessed_net_usd"],
                "overnight_gap_usd": heads["overnight_gap_usd"],
                "path_p50_curve": heads["path_p50_curve"],
                "reasoning": reasoning,
                "plays_fired": list(plays_fired),
                "plays_stood_down": list(plays_stood_down),
                "confidence": heads["confidence"],
                "state_defects_and_gaps_reported": [],
                "disposition": disposition,
            }
            checked = validate_bld1(payload)
        except ContractError as exc:
            return self.abstain(
                date, [f"contract_violation: {exc}"], packet_hash, model_version, reasoning
            )
        except (KeyError, TypeError, ValueError) as exc:
            return self.abstain(
                date,
                [f"head_output_malformed: {type(exc).__name__}: {exc}"],
                packet_hash,
                model_version,
                reasoning,
            )

        return BLDRecord(
            payload=checked,
            packet_hash=packet_hash,
            model_version=model_version,
            calibrator_version=self.calibrator_version,
        )

    def project_internal(
        self,
        date: str,
        heads: InternalBLD1Heads,
        packet_hash: str,
        model_version: str,
        packet_defects: Sequence[str] = (),
        reasoning: str = "",
        plays_fired: Sequence[str] = (),
        plays_stood_down: Sequence[str] = (),
        disposition: Disposition | str = Disposition.CALL,
    ) -> BLDRecord:
        """Project only the four deliberately mapped learned quantities.

        This typed entry point adds the semantic close-to-close/gap/path check
        before delegating to the same total BLD-1 validator and safety boundary.
        """
        date = self._check_context(date)
        if packet_defects:
            return self.abstain(
                date, list(packet_defects), packet_hash, model_version, reasoning
            )
        if not isinstance(heads, InternalBLD1Heads):
            return self.abstain(
                date,
                ["head_output_malformed: expected InternalBLD1Heads"],
                packet_hash,
                model_version,
                reasoning,
            )

        mapped = heads.bld1_projection()
        try:
            net = float(mapped["guessed_net_usd"])
            gap = float(mapped["overnight_gap_usd"])
            curve = mapped["path_p50_curve"]
            if not isinstance(curve, (list, tuple)) or not curve:
                raise ValueError("path_p50_curve must be a non-empty sequence")
            if not isinstance(curve[-1], (list, tuple)) or len(curve[-1]) != 2:
                raise ValueError(
                    "path_p50_curve points must be [et_time, cumulative_usd]"
                )
            terminal = float(curve[-1][1])
            expected_terminal = net - gap
            if not math.isclose(
                terminal, expected_terminal, rel_tol=0.0, abs_tol=1.0
            ):
                raise ValueError(
                    "path_p50_curve endpoint "
                    f"{terminal} != guessed_net_usd - overnight_gap_usd "
                    f"({expected_terminal})"
                )
        except (TypeError, ValueError, OverflowError) as exc:
            return self.abstain(
                date,
                [f"head_output_malformed: {exc}"],
                packet_hash,
                model_version,
                reasoning,
            )

        return self.project(
            date=date,
            heads=mapped,
            packet_hash=packet_hash,
            model_version=model_version,
            reasoning=reasoning,
            plays_fired=plays_fired,
            plays_stood_down=plays_stood_down,
            disposition=disposition,
        )
