#!/usr/bin/env python3
"""
brain_audit.py - the 82-play audit harness, IN THE REPO. (S111, fixing an S111 defect.)

WHY THIS FILE EXISTS, and it is not a flattering reason. The S111 audit ran as a workflow whose
script lived under the user's home `.claude/projects/...`, i.e. session scratchpad. The S111 drop-in
then pointed the next session at that path. S112 checked, found `git ls-files | grep brain-play-audit`
returns ZERO, and correctly named it another instance of the A-7 disease - the machine that did the
work living outside the store - written in the same session that diagnosed the disease. This file is
the correction: the harness is committed, so the audit is re-runnable by anyone, forever.

It is also the FIRST INSTANCE OF THE A-7 PATTERN done properly: the prompt is GENERATED BY LOOKUP
from the brain rather than transcribed by hand. Slot values come from `knowledge/ng_brain.json`;
nobody types a play id. That is the same fix A-7 proposes for RUN_SOP.md's 13 hand-filled slots.

WHAT THE AUDIT DOES, per play, in two halves:
  HALF A - CLASSIFY THE SUPPORT. What does this play actually rest on?
  HALF B - THE D24 CORPUS SEARCH. A mechanism is n=1 until the corpus is searched.

USAGE
    python brain_audit.py prompts                 # emit all batch prompts (spawn these)
    python brain_audit.py prompts --batch 3       # just one
    python brain_audit.py validate out.json       # check a returned batch against the schema
    python brain_audit.py collect forecasts/brain_audit/*.json   # merge + population report
    python brain_audit.py rubric                  # print the rubric alone
"""

import argparse
import glob as _glob
import json
import os
import sys
from collections import Counter, OrderedDict

HERE = os.path.dirname(os.path.abspath(__file__))
BRAIN = os.path.join(HERE, "knowledge", "ng_brain.json")
OUTDIR = os.path.join(HERE, "forecasts", "brain_audit")
N_BATCHES = 8

SUPPORT_CLASSES = ["MECHANISM_VERIFIED", "NOVEL_N1", "OUTCOME_CREDITED", "ASSERTED",
                   "NOT_A_PLAY", "UNCLEAR"]
D24_STATES = ["found", "searched_none", "not_searched"]
RECOMMENDATIONS = ["keep", "scope_narrower", "forward_test_on_next_group",
                   "needs_reading_by_greg", "cannot_assess"]

# --------------------------------------------------------------------------------------
# THE RUBRIC. Corrected S111 after Greg's instruction and S112's Q1.
# --------------------------------------------------------------------------------------
RUBRIC = """
SUPPORT CLASSES - the discriminator matters more than the label, so read all six before choosing.

  MECHANISM_VERIFIED  A causal argument PLUS measurement that could have come out the other way.
                      Counts, rates, n across groups, monotone relationships, out-of-sample checks.
                      Test: could this evidence have falsified the play? If not, it is not this.

  NOVEL_N1            An ARGUED MECHANISM with a NAMED FIRST INSTANCE traced to a posterior or an
                      actual - seen once, honestly labelled. THIS IS NOT A WEAK CLASS.
                      Greg, S111: "some things won't have past instances because it was the first
                      time we saw them but that doesn't make them bad." D24 already says a finding
                      is never disregarded for lacking past evidence. Anything genuinely new has no
                      precedent BY CONSTRUCTION - the tropical channel has none at all.
                      DISCRIMINATOR vs ASSERTED: NOVEL_N1 has a mechanism AND a traced instance.
                      ASSERTED has neither.

  OUTCOME_CREDITED    The support is that a day (or days) delivered the expected move; the mechanism
                      was INFERRED FROM THE OUTCOME rather than tested independently. THIS IS THE
                      S108 SIGNATURE and it is the main thing you are hunting. Documented instance:
                      S108 credited D's pre-print generator with 2,090 from day nets, the intraday
                      check was never run, G21 later refuted the timing limb 1-of-4, and s103.6 had
                      to retract it. Right answer, wrong reason, merged.

  ASSERTED            A claim with no mechanism argued and no traced instance, or "evidence" that
                      merely restates the claim.

  NOT_A_PLAY          The entry is not a conditional rule at all and support classification does not
                      apply. Use for DESCRIPTOR-grade regime context and for WIRED_UNPROVEN feeds.
                      WORKED CASE (S112 caught this): supply.lng_export_throughput_vessel_line is a
                      feed merged on Greg's instruction to make a live channel readable, with zero
                      consumers. It is an INSTRUMENT, not a mechanism. Forcing it into ASSERTED is a
                      category error. Say what it is and move on.

  UNCLEAR             You genuinely cannot tell. Say what would settle it.

DO NOT BE GENEROUS. A number in the evidence field is not a measurement if it is the outcome the
play was written to explain. The question to hold throughout: COULD THIS EVIDENCE HAVE COME OUT THE
OTHER WAY?

THE D24 CORPUS SEARCH - record ONE of three, and never collapse them:
  found          instances located WITH context. Say how many and name them.
  searched_none  you searched and there are none. A REAL RESULT, not a failure - it means the
                 mechanism is regime-specific or genuinely new.
  not_searched   you could not search (field not served, group not staged, quantity is price content
                 masked by design). Say what would settle it.

INSTANCE DISCIPLINE. The ledgers are NARRATIVE and repeat the same claim across documents, which
makes one instance look like several. An instance counts ONLY if you can trace it to a POSTERIOR or
an ACTUAL - a date, a number, a file. Prose citing prose is one instance, not two. Name the file.

ALSO CHECK, because it is cheap and it decides usability: CAN THE CONDITION CHANGE STATE? If the
play carries a numeric bar on a served quantity, does that bar actually split days within a block,
or is it 0-of-10 / 10-of-10? Measured examples: gw_hdd >= 16.4 fires 12/12 in g11 and g12 but 0/10
in all four summer blocks; the burn gate's d_gw_cdd limb was positive 20/20 across two groups.
A condition that cannot change state carries no information whatever form it is written in.

RULES OF CONDUCT. You are AUDITING, not fixing. Do not edit knowledge/ng_brain.json or any posterior
- they are the record. Nothing is deleted on your say-so: the standing policy (D31) is that a
refutation is SCOPED to the cell and instrument it was measured on, never converted into "dead".
"This play is well supported" is as useful a finding as a bad one.
"""

CORPUS = """
SEARCHABLE AND COMMITTED (groups g6-g23; actuals g17-g23; modern served state g18-g23):
  forecasts/grp<N>.json                        assembled BLIND forecasts (immutable records)
  forecasts/g<N>_blind_round1/                 archived blind per-specialist posteriors (G19-G22)
  forecasts/g<N>_perday/                       blind per-day posteriors (G22, G23)
  forecasts/g<N>_refine_perday/                refine per-day posteriors (G22, G23)
  forecasts/grp<N>_mbo_specialist_*.json       REFINE posteriors (canonical names, post-archive)
  forecasts/grp<N>_mbo_refined.json            assembled refine
  renders/ng_refine_s95/grp<N>_state.json      the served decision state per day
  renders/ng_refine_s95/g<N>_actual.json       realized day_move_usd, gap, close per day
  renders/ng_refine_s95/g<N>_mbo_evidence.json replayed tape evidence
  G22_REASONING_LEDGER_S109.md, G22_REFINE_LEDGER_S110.md, G23_BLIND_LEDGER_S110.md,
  G23_REFINE_LEDGER_S110.md, S102_MERGE_PROPOSAL.md, S109_MERGE_PROPOSAL_G22.md
  BRAIN_AUDIT_PARTIAL_S111.json  - 32 plays already audited in S111 under the OLD rubric (which
      lacked NOVEL_N1 and NOT_A_PLAY). Useful as a cross-check, NOT as an answer: three plays it
      classed ASSERTED need re-reading under the corrected rubric.
"""


def load_plays():
    b = json.load(open(BRAIN, encoding="utf-8"))
    return b, [p["id"] for p in b["plays"]]


def batches(ids, n=N_BATCHES):
    """deterministic interleave, so batch membership is reproducible across runs."""
    return [ids[i::n] for i in range(n)]


def schema():
    return {
        "type": "object", "additionalProperties": False,
        "required": ["batch_index", "audits", "batch_observations"],
        "properties": {
            "batch_index": {"type": "integer"},
            "batch_observations": {"type": "string"},
            "audits": {"type": "array", "items": {
                "type": "object", "additionalProperties": False,
                "required": ["play_id", "support_class", "the_argument",
                             "could_evidence_have_come_out_otherwise", "d24_state", "instances",
                             "condition_can_change_state", "falsifier", "recommendation", "confidence"],
                "properties": {
                    "play_id": {"type": "string"},
                    "support_class": {"type": "string", "enum": SUPPORT_CLASSES},
                    "the_argument": {"type": "string"},
                    "could_evidence_have_come_out_otherwise": {"type": "string"},
                    "d24_state": {"type": "string", "enum": D24_STATES},
                    "instances": {"type": "array", "items": {
                        "type": "object", "additionalProperties": False,
                        "required": ["date", "group", "source_file", "what_the_state_said",
                                     "what_the_day_did", "supports_or_contradicts"],
                        "properties": {
                            "date": {"type": "string"}, "group": {"type": "string"},
                            "source_file": {"type": "string"},
                            "what_the_state_said": {"type": "string"},
                            "what_the_day_did": {"type": "string"},
                            "supports_or_contradicts": {"type": "string",
                                                        "enum": ["supports", "contradicts", "ambiguous"]}}}},
                    "condition_can_change_state": {"type": "string"},
                    "falsifier": {"type": "string"},
                    "recommendation": {"type": "string", "enum": RECOMMENDATIONS},
                    "confidence": {"type": "string", "enum": ["low", "med", "high"]}}}}}}


def prompt_for(i, ids, brain_ver):
    return f"""You are auditing the NG forecaster's brain, batch {i} of {N_BATCHES}.

CWD for all commands: research/kalshi   (python with numpy/pandas available)
Brain: knowledge/ng_brain.json (version {brain_ver}, schema brain-schema-1)

WHY THIS AUDIT EXISTS. Until S111 the output contract required a numeric magnitude on every day and
the coordinator hard-failed on anything else, so a specialist with NO genuine read still had to emit
a number - and would construct a rationale to justify it. Measured across 50 blind days carrying a
declared confidence: exactly ONE was declared high, and the confidence field does not discriminate
accuracy at all (low slightly outperforms med). So the corpus contains an unknown fraction of
manufactured reasoning that is indistinguishable downstream from real reasoning. Blind reasoning does
not merge directly - it reaches the brain through refine proposal, adjudication and merge - so the
path you are hunting is subtler: a blind call is RIGHT ON THE DAY NET, the refine credits the
mechanism, nobody runs the intraday check, and a false mechanism enters the brain attached to a
correct outcome.

YOUR BATCH ({len(ids)} plays). Audit EVERY one. Read each in full from the brain by its id:
{chr(10).join('  - ' + x for x in ids)}
{RUBRIC}
{CORPUS}

OUTPUT. Write forecasts/brain_audit/batch_{i}.json with EXACTLY this shape:
{json.dumps(schema(), indent=1)}

Then run: python brain_audit.py validate forecasts/brain_audit/batch_{i}.json
and fix anything it rejects before returning. Return a concise prose summary of the batch.
"""


def cmd_prompts(a):
    brain, ids = load_plays()
    ver = brain.get("meta", {}).get("version", "?")
    bs = batches(ids)
    sel = [a.batch] if a.batch is not None else range(N_BATCHES)
    for i in sel:
        print("=" * 92)
        print("BATCH %d PROMPT  (%d plays)  - spawn this verbatim" % (i, len(bs[i])))
        print("=" * 92)
        print(prompt_for(i, bs[i], ver))
    return 0


def cmd_validate(a):
    try:
        d = json.load(open(a.path, encoding="utf-8"))
    except Exception as e:
        print("FAIL unreadable: %s" % e)
        return 1
    brain, ids = load_plays()
    expected = set(batches(ids)[d.get("batch_index", -1)]) if isinstance(d.get("batch_index"), int) \
        and 0 <= d["batch_index"] < N_BATCHES else None
    errs = []
    seen = set()
    for r in d.get("audits", []):
        pid = r.get("play_id")
        seen.add(pid)
        if pid not in ids:
            errs.append("unknown play_id %s" % pid)
        for f in schema()["properties"]["audits"]["items"]["required"]:
            if f not in r:
                errs.append("%s missing %s" % (pid, f))
        if r.get("support_class") not in SUPPORT_CLASSES:
            errs.append("%s bad support_class %s" % (pid, r.get("support_class")))
        if r.get("d24_state") not in D24_STATES:
            errs.append("%s bad d24_state %s" % (pid, r.get("d24_state")))
        if r.get("d24_state") == "found" and not r.get("instances"):
            errs.append("%s says d24_state=found but lists no instances" % pid)
        for ins in r.get("instances", []):
            if not ins.get("source_file"):
                errs.append("%s instance %s has no source_file (prose citing prose does not count)"
                            % (pid, ins.get("date")))
    if expected is not None:
        missing = expected - seen
        if missing:
            errs.append("batch incomplete, %d plays not audited: %s" % (len(missing), sorted(missing)))
    print("%s  %d plays, %d errors" % ("FAIL" if errs else "PASS", len(seen), len(errs)))
    for e in errs[:40]:
        print("   " + e)
    return 1 if errs else 0


def cmd_collect(a):
    files = []
    for pat in a.paths:
        files.extend(_glob.glob(pat))
    audits = []
    for f in sorted(files):
        d = json.load(open(f, encoding="utf-8"))
        audits.extend(d.get("audits", []))
    brain, ids = load_plays()
    print("collected %d play audits from %d files (brain has %d plays)" % (len(audits), len(files), len(ids)))
    print("\nSUPPORT CLASS:")
    for k, v in Counter(x.get("support_class") for x in audits).most_common():
        print("   %-20s %3d" % (k, v))
    print("\nD24 CORPUS STATE:")
    for k, v in Counter(x.get("d24_state") for x in audits).most_common():
        print("   %-16s %3d" % (k, v))
    print("\nRECOMMENDATION:")
    for k, v in Counter(x.get("recommendation") for x in audits).most_common():
        print("   %-28s %3d" % (k, v))
    ni = sum(len(x.get("instances") or []) for x in audits)
    print("\ninstances traced: %d across %d plays" % (ni, sum(1 for x in audits if x.get("instances"))))
    miss = set(ids) - {x.get("play_id") for x in audits}
    print("plays NOT yet audited: %d %s" % (len(miss), sorted(miss)[:8] if miss else ""))
    if a.out:
        os.makedirs(os.path.dirname(a.out) or ".", exist_ok=True)
        json.dump({"n_plays": len(ids), "audits": audits}, open(a.out, "w", encoding="utf-8"),
                  indent=1, ensure_ascii=False)
        print("\nwrote %s" % a.out)
    return 0


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest="cmd", required=True)
    p = sub.add_parser("prompts"); p.add_argument("--batch", type=int, default=None)
    p = sub.add_parser("validate"); p.add_argument("path")
    p = sub.add_parser("collect"); p.add_argument("paths", nargs="+"); p.add_argument("--out")
    sub.add_parser("rubric")
    a = ap.parse_args()
    if a.cmd == "prompts":
        return cmd_prompts(a)
    if a.cmd == "validate":
        return cmd_validate(a)
    if a.cmd == "collect":
        return cmd_collect(a)
    print(RUBRIC)
    return 0


if __name__ == "__main__":
    sys.exit(main())
