#!/usr/bin/env python3
"""
brain_audit.py - the 82-play audit harness, IN THE REPO. (S111, fixing an S111 defect.)

WHY THIS FILE EXISTS, and it is not a flattering reason. The S111 audit ran as a workflow whose
script lived under the user's home `.claude/projects/...`, i.e. session scratchpad. The S111 drop-in
then pointed the next session at that path. S112 checked, found `git ls-files | grep brain-play-audit`
returns ZERO, and correctly named it another instance of the A-7 disease - the machine that did the
work living outside the store - written in the same session that diagnosed the disease. This file is
the correction: the harness is committed, so the audit is re-runnable by anyone, forever.

It is also the FIRST INSTANCE OF THE A-7 PATTERN done properly: the prompt is GENERATED BY LOOKUP
from the brain rather than transcribed by hand. Slot values come from `knowledge/ng_brain.json`;
nobody types a play id. That is the same fix A-7 proposes for RUN_SOP.md's 13 hand-filled slots.

WHAT THE AUDIT DOES, per play, in two halves:
  HALF A - CLASSIFY THE SUPPORT. What does this play actually rest on?
  HALF B - THE D24 CORPUS SEARCH. A mechanism is n=1 until the corpus is searched.

USAGE
    python brain_audit.py prompts                 # emit all batch prompts (spawn these)
    python brain_audit.py prompts --batch 3       # just one
    python brain_audit.py validate out.json       # check a returned batch against the schema
    python brain_audit.py collect forecasts/brain_audit/*.json   # merge + population report
    python brain_audit.py rubric                  # print the rubric alone
"""

import argparse
import re
import glob as _glob
import json
import os
import sys
from collections import Counter, OrderedDict

HERE = os.path.dirname(os.path.abspath(__file__))
BRAIN = os.path.join(HERE, "knowledge", "ng_brain.json")
OUTDIR = os.path.join(HERE, "forecasts", "brain_audit")
ROOT = os.path.dirname(os.path.dirname(HERE))
N_BATCHES = 8


_BASENAMES = None


def _corpus_basenames():
    """One-time index of every committed corpus file by basename, so a citation that names a real
    file without its directory still resolves."""
    global _BASENAMES
    if _BASENAMES is None:
        _BASENAMES = {}
        for d in (os.path.join(HERE, "forecasts"), os.path.join(HERE, "renders", "ng_refine_s95")):
            for p in _glob.glob(os.path.join(d, "**", "*.json"), recursive=True):
                _BASENAMES.setdefault(os.path.basename(p), p)
    return _BASENAMES


def _expand_braces(s):
    """g{17..23}_actual.json and g{18,20,22}_actual.json are how the S111 auditors cited a span.
    Expand both forms so a range citation is checked as the files it names."""
    m = re.search(r"\{([^{}]*)\}", s)
    if not m:
        return _expand_bare_range(s)
    body, out = m.group(1), []
    rng = re.fullmatch(r"(\d+)\.\.(\d+)", body.strip())
    items = ([str(i) for i in range(int(rng.group(1)), int(rng.group(2)) + 1)] if rng
             else [x.strip() for x in body.split(",") if x.strip()])
    for it in items:
        out.extend(_expand_braces(s[:m.start()] + it + s[m.end():]))
    return out


def _expand_bare_range(s):
    """The other span shorthand, without braces: g17..g23_mbo_evidence.json,
    grp6..grp23_state.json. Same intent, different keyboard."""
    m = re.search(r"([A-Za-z]+)(\d+)\.\.(?:\1)?(\d+)", s)
    if not m:
        return [s]
    pre, lo, hi = m.group(1), int(m.group(2)), int(m.group(3))
    if hi < lo or hi - lo > 100:
        return [s]
    return [s[:m.start()] + pre + str(i) + s[m.end():] for i in range(lo, hi + 1)]


def _split_citation(sf):
    """Split a source_file into the files it names. Splits on + ; and commas, but NEVER on a
    comma inside braces - g{18,20,22}_actual.json is ONE citation, and splitting it produced a
    false failure on real S111 instances before this was fixed."""
    parts, buf, depth = [], "", 0
    for ch in str(sf):
        if ch == "{":
            depth += 1
        elif ch == "}":
            depth = max(0, depth - 1)
        if depth == 0 and (ch in "+;," ):
            parts.append(buf); buf = ""
            continue
        buf += ch
    parts.append(buf)
    # "grp22_C_20260623.json, _20260630.json" - a bare _suffix continues the previous prefix.
    out, prev = [], None
    for p in parts:
        p = p.strip()
        if not p:
            continue
        if p.startswith("_") and prev:
            # A bare _suffix continues the previous citation: "grp22_C_20260623.json, _20260630.json"
            # inherits grp22_C, while "grp23_B_20260706.json, _C_20260707.json" inherits only grp23.
            # Rather than special-case each shape, try progressively shorter prefixes of the
            # previous stem and keep the first that actually resolves. Special-casing the first
            # shape rebuilt grp22_20260630.json - a file that does not exist - which would have
            # read downstream as a fabricated citation.
            head = prev.rsplit("/", 1)
            d_, fname = (head[0] + "/", head[1]) if len(head) > 1 else ("", head[0])
            toks = re.sub(r"\.json$", "", fname).split("_")
            suffix = p.lstrip("_")
            cand = None
            for k in range(len(toks), 0, -1):
                trial = d_ + "_".join(toks[:k]) + "_" + suffix
                if _resolves(trial):
                    cand = trial
                    break
            p = cand or (d_ + toks[0] + "_" + suffix)
        out.append(p)
        prev = p
    return out


def _is_machine_path(tok):
    """A drive letter or an absolute filesystem path is a DESKTOP path. Greg, S112: "all of this
    stuff is going to live in aws or git so there should be no paths from my desktop." Same rule
    as D33 and for the same reason - a citation nobody else can open is a broken citation, and
    silently re-rooting it would hide the defect instead of fixing it. The S111 auditors emitted
    E:/Markets/... from Greg's box; those citations need rewriting repo-relative."""
    t = tok.strip().strip("`'\"")
    return bool(re.match(r"^[A-Za-z]:[/\\]", t)) or t.startswith("/") or t.startswith("~")


def _resolves(tok):
    """One path token -> does it name anything real in this repo, cited portably?"""
    tok = tok.strip().strip("`'\"").rstrip(".,;")
    if not tok or _is_machine_path(tok):
        return False
    for cand in _expand_braces(tok):
        for base in (ROOT, HERE):
            full = os.path.join(base, cand)
            if os.path.exists(full):          # file OR directory
                return True
            if _glob.glob(full):              # a wildcard that matches something
                return True
        if os.path.basename(cand) in _corpus_basenames():
            return True
    return False


def _traces(source_file):
    """Does this instance's source_file RESOLVE to real evidence in this repo?

    THE TRACEABILITY WALL (D32 s3): an instance counts only if it traces to a posterior or an
    actual - a date, a number, A FILE. Checking the field is merely PRESENT is not the same as
    checking it RESOLVES, and presence-without-correctness is this desk's signature defect
    (holes #7, #8 and #9 were all well-formed and wrong). Measured before this existed: a batch
    citing `forecasts/grp22_C_NEVER_EXISTED.json` validated PASS with zero errors.

    Calibrated against the 140 real instances in BRAIN_AUDIT_PARTIAL_S111.json rather than
    written from an idea of what a citation looks like - and the first draft, which required one
    literal path, would have failed 93 of those 140 legitimately-cited instances. A guard that
    always shows red is one people learn to ignore (D33's own lesson), so the shorthand the
    auditors actually use is handled: multiple files joined by + ; or , a trailing annotation,
    a brace range, a bare X..Y range, a glob, and a bare directory.

    What is NOT handled, deliberately: a desktop path. Greg, S112: "all of this stuff is going to
    live in aws or git so there should be no paths from my desktop." Everything must be cited
    repo-relative, so E:/Markets/... FAILS rather than being silently re-rooted."""
    parts = _split_citation(source_file)
    if not parts:
        return False
    for p in parts:
        # a trailing prose annotation is allowed: "…/grp23_state_audit.json finding f4"
        if not any(_resolves(tok) for tok in (p, p.split()[0])):
            return False
    return True

SUPPORT_CLASSES = ["MECHANISM_VERIFIED", "NOVEL_N1", "OUTCOME_CREDITED", "ASSERTED",
                   "NOT_A_PLAY", "UNCLEAR"]
D24_STATES = ["found", "searched_none", "not_searched"]
RECOMMENDATIONS = ["keep", "scope_narrower", "forward_test_on_next_group",
                   "needs_reading_by_greg", "cannot_assess"]

# --------------------------------------------------------------------------------------
# THE RUBRIC. Corrected S111 after Greg's instruction and S112's Q1.
# --------------------------------------------------------------------------------------
RUBRIC = """
SUPPORT CLASSES - the discriminator matters more than the label, so read all six before choosing.

  MECHANISM_VERIFIED  A causal argument PLUS measurement that could have come out the other way.
                      Counts, rates, n across groups, monotone relationships, out-of-sample checks.
                      Test: could this evidence have falsified the play? If not, it is not this.

  NOVEL_N1            An ARGUED MECHANISM with a NAMED FIRST INSTANCE traced to a posterior or an
                      actual - seen once, honestly labelled. THIS IS NOT A WEAK CLASS.
                      Greg, S111: "some things won't have past instances because it was the first
                      time we saw them but that doesn't make them bad." D24 already says a finding
                      is never disregarded for lacking past evidence. Anything genuinely new has no
                      precedent BY CONSTRUCTION - the tropical channel has none at all.
                      DISCRIMINATOR vs ASSERTED: NOVEL_N1 has a mechanism AND a traced instance.
                      ASSERTED has neither.

  OUTCOME_CREDITED    The support is that a day (or days) delivered the expected move; the mechanism
                      was INFERRED FROM THE OUTCOME rather than tested independently. THIS IS THE
                      S108 SIGNATURE and it is the main thing you are hunting. Documented instance:
                      S108 credited D's pre-print generator with 2,090 from day nets, the intraday
                      check was never run, G21 later refuted the timing limb 1-of-4, and s103.6 had
                      to retract it. Right answer, wrong reason, merged.

  ASSERTED            A claim with no mechanism argued and no traced instance, or "evidence" that
                      merely restates the claim.

  NOT_A_PLAY          The entry is not a conditional rule at all and support classification does not
                      apply. Use for DESCRIPTOR-grade regime context and for WIRED_UNPROVEN feeds.
                      WORKED CASE (S112 caught this): supply.lng_export_throughput_vessel_line is a
                      feed merged on Greg's instruction to make a live channel readable, with zero
                      consumers. It is an INSTRUMENT, not a mechanism. Forcing it into ASSERTED is a
                      category error. Say what it is and move on.

  UNCLEAR             You genuinely cannot tell. Say what would settle it.

DO NOT BE GENEROUS. A number in the evidence field is not a measurement if it is the outcome the
play was written to explain. The question to hold throughout: COULD THIS EVIDENCE HAVE COME OUT THE
OTHER WAY?

THE D24 CORPUS SEARCH - record ONE of three, and never collapse them:
  found          instances located WITH context. Say how many and name them.
  searched_none  you searched and there are none. A REAL RESULT, not a failure - it means the
                 mechanism is regime-specific or genuinely new.
  not_searched   you could not search (field not served, group not staged, quantity is price content
                 masked by design). Say what would settle it.

INSTANCE DISCIPLINE. The ledgers are NARRATIVE and repeat the same claim across documents, which
makes one instance look like several. An instance counts ONLY if you can trace it to a POSTERIOR or
an ACTUAL - a date, a number, a file. Prose citing prose is one instance, not two. Name the file.

ALSO CHECK, because it is cheap and it decides usability: CAN THE CONDITION CHANGE STATE? If the
play carries a numeric bar on a served quantity, does that bar actually split days within a block,
or is it 0-of-10 / 10-of-10? Measured examples: gw_hdd >= 16.4 fires 12/12 in g11 and g12 but 0/10
in all four summer blocks; the burn gate's d_gw_cdd limb was positive 20/20 across two groups.
A condition that cannot change state carries no information whatever form it is written in.

RULES OF CONDUCT. You are AUDITING, not fixing. Do not edit knowledge/ng_brain.json or any posterior
- they are the record. Nothing is deleted on your say-so: the standing policy (D31) is that a
refutation is SCOPED to the cell and instrument it was measured on, never converted into "dead".
"This play is well supported" is as useful a finding as a bad one.
"""

CORPUS = """
SEARCHABLE AND COMMITTED (groups g6-g23; actuals g17-g23; modern served state g18-g23):
  forecasts/grp<N>.json                        assembled BLIND forecasts (immutable records)
  forecasts/g<N>_blind_round1/                 archived blind per-specialist posteriors (G19-G22)
  forecasts/g<N>_perday/                       blind per-day posteriors (G22, G23)
  forecasts/g<N>_refine_perday/                refine per-day posteriors (G22, G23)
  forecasts/grp<N>_mbo_specialist_*.json       REFINE posteriors (canonical names, post-archive)
  forecasts/grp<N>_mbo_refined.json            assembled refine
  renders/ng_refine_s95/grp<N>_state.json      the served decision state per day
  renders/ng_refine_s95/g<N>_actual.json       realized day_move_usd, gap, close per day
  renders/ng_refine_s95/g<N>_mbo_evidence.json replayed tape evidence
  G22_REASONING_LEDGER_S109.md, G22_REFINE_LEDGER_S110.md, G23_BLIND_LEDGER_S110.md,
  G23_REFINE_LEDGER_S110.md, S102_MERGE_PROPOSAL.md, S109_MERGE_PROPOSAL_G22.md
  BRAIN_AUDIT_PARTIAL_S111.json  - 32 plays already audited in S111 under the OLD rubric (which
      lacked NOVEL_N1 and NOT_A_PLAY). Useful as a cross-check, NOT as an answer: three plays it
      classed ASSERTED need re-reading under the corrected rubric.
"""


def load_plays():
    b = json.load(open(BRAIN, encoding="utf-8"))
    return b, [p["id"] for p in b["plays"]]


def batches(ids, n=N_BATCHES):
    """deterministic interleave, so batch membership is reproducible across runs."""
    return [ids[i::n] for i in range(n)]


def schema():
    return {
        "type": "object", "additionalProperties": False,
        "required": ["batch_index", "audits", "batch_observations"],
        "properties": {
            "batch_index": {"type": "integer"},
            "batch_observations": {"type": "string"},
            "audits": {"type": "array", "items": {
                "type": "object", "additionalProperties": False,
                "required": ["play_id", "support_class", "the_argument",
                             "could_evidence_have_come_out_otherwise", "d24_state", "instances",
                             "condition_can_change_state", "falsifier", "recommendation", "confidence"],
                "properties": {
                    "play_id": {"type": "string"},
                    "support_class": {"type": "string", "enum": SUPPORT_CLASSES},
                    "the_argument": {"type": "string"},
                    "could_evidence_have_come_out_otherwise": {"type": "string"},
                    "d24_state": {"type": "string", "enum": D24_STATES},
                    "instances": {"type": "array", "items": {
                        "type": "object", "additionalProperties": False,
                        "required": ["date", "group", "source_file", "what_the_state_said",
                                     "what_the_day_did", "supports_or_contradicts"],
                        "properties": {
                            "date": {"type": "string"}, "group": {"type": "string"},
                            "source_file": {"type": "string"},
                            "what_the_state_said": {"type": "string"},
                            "what_the_day_did": {"type": "string"},
                            "supports_or_contradicts": {"type": "string",
                                                        "enum": ["supports", "contradicts", "ambiguous"]}}}},
                    "condition_can_change_state": {"type": "string"},
                    "falsifier": {"type": "string"},
                    "recommendation": {"type": "string", "enum": RECOMMENDATIONS},
                    "confidence": {"type": "string", "enum": ["low", "med", "high"]}}}}}}


def prompt_for(i, ids, brain_ver):
    return f"""You are auditing the NG forecaster's brain, batch {i} of {N_BATCHES}.

CWD for all commands: research/kalshi   (python with numpy/pandas available)
Brain: knowledge/ng_brain.json (version {brain_ver}, schema brain-schema-1)

WHY THIS AUDIT EXISTS. Until S111 the output contract required a numeric magnitude on every day and
the coordinator hard-failed on anything else, so a specialist with NO genuine read still had to emit
a number - and would construct a rationale to justify it. Measured across 50 blind days carrying a
declared confidence: exactly ONE was declared high, and the confidence field does not discriminate
accuracy at all (low slightly outperforms med). So the corpus contains an unknown fraction of
manufactured reasoning that is indistinguishable downstream from real reasoning. Blind reasoning does
not merge directly - it reaches the brain through refine proposal, adjudication and merge - so the
path you are hunting is subtler: a blind call is RIGHT ON THE DAY NET, the refine credits the
mechanism, nobody runs the intraday check, and a false mechanism enters the brain attached to a
correct outcome.

YOUR BATCH ({len(ids)} plays). Audit EVERY one. Read each in full from the brain by its id:
{chr(10).join('  - ' + x for x in ids)}
{RUBRIC}
{CORPUS}

OUTPUT. Write forecasts/brain_audit/batch_{i}.json with EXACTLY this shape:
{json.dumps(schema(), indent=1)}

Then run: python brain_audit.py validate forecasts/brain_audit/batch_{i}.json
and fix anything it rejects before returning. Return a concise prose summary of the batch.
"""


def cmd_prompts(a):
    brain, ids = load_plays()
    ver = brain.get("meta", {}).get("version", "?")
    bs = batches(ids)
    sel = [a.batch] if a.batch is not None else range(N_BATCHES)
    for i in sel:
        print("=" * 92)
        print("BATCH %d PROMPT  (%d plays)  - spawn this verbatim" % (i, len(bs[i])))
        print("=" * 92)
        print(prompt_for(i, bs[i], ver))
    return 0


def cmd_validate(a):
    try:
        d = json.load(open(a.path, encoding="utf-8"))
    except Exception as e:
        print("FAIL unreadable: %s" % e)
        return 1
    brain, ids = load_plays()
    expected = set(batches(ids)[d.get("batch_index", -1)]) if isinstance(d.get("batch_index"), int) \
        and 0 <= d["batch_index"] < N_BATCHES else None
    errs = []
    seen = set()
    for r in d.get("audits", []):
        pid = r.get("play_id")
        seen.add(pid)
        if pid not in ids:
            errs.append("unknown play_id %s" % pid)
        for f in schema()["properties"]["audits"]["items"]["required"]:
            if f not in r:
                errs.append("%s missing %s" % (pid, f))
        if r.get("support_class") not in SUPPORT_CLASSES:
            errs.append("%s bad support_class %s" % (pid, r.get("support_class")))
        if r.get("d24_state") not in D24_STATES:
            errs.append("%s bad d24_state %s" % (pid, r.get("d24_state")))
        if r.get("d24_state") == "found" and not r.get("instances"):
            errs.append("%s says d24_state=found but lists no instances" % pid)
        # The mirror check. searched_none and not_searched are REAL RESULTS (D24 states b and c),
        # so a record claiming either while listing instances is incoherent in the direction that
        # would silently under-count the corpus.
        if r.get("d24_state") in ("searched_none", "not_searched") and r.get("instances"):
            errs.append("%s says d24_state=%s but lists %d instances"
                        % (pid, r.get("d24_state"), len(r.get("instances"))))
        for ins in r.get("instances", []):
            if not ins.get("source_file"):
                errs.append("%s instance %s has no source_file (prose citing prose does not count)"
                            % (pid, ins.get("date")))
            elif any(_is_machine_path(t) for t in _split_citation(ins["source_file"])):
                # Greg, S112: everything lives in AWS or git, so a desktop path is a defect even
                # when the file it names is real. Same rule as D33, same reason.
                errs.append("%s instance %s: DESKTOP PATH - cite repo-relative, everything lives "
                            "in git or S3: %s" % (pid, ins.get("date"), ins["source_file"]))
            elif not _traces(ins["source_file"]):
                # THE TRACEABILITY WALL. D32 s3: an instance counts only if it traces to a posterior
                # or an actual - a date, a number, A FILE. Checking the field is PRESENT is not the
                # same as checking it RESOLVES, and presence-without-correctness is this desk's
                # signature defect (holes #7, #8, #9 were all well-formed and wrong). Measured
                # before this check existed: a batch citing a grp22 posterior that never existed
                # validated PASS with 0 errors. The audit's whole output is instances, and S111-3
                # writes them INTO the brain, so an untraceable one becomes permanent evidence.
                errs.append("%s instance %s: source_file does not exist: %s"
                            % (pid, ins.get("date"), ins["source_file"]))
        if pid in ids and expected is not None and pid not in expected:
            errs.append("%s is not in this batch (audited by another batch - possible double count)"
                        % pid)
    if expected is not None:
        missing = expected - seen
        if missing:
            errs.append("batch incomplete, %d plays not audited: %s" % (len(missing), sorted(missing)))
    print("%s  %d plays, %d errors" % ("FAIL" if errs else "PASS", len(seen), len(errs)))
    for e in errs[:40]:
        print("   " + e)
    return 1 if errs else 0


def cmd_collect(a):
    files = []
    for pat in a.paths:
        files.extend(_glob.glob(pat))
    audits = []
    for f in sorted(files):
        d = json.load(open(f, encoding="utf-8"))
        audits.extend(d.get("audits", []))
    brain, ids = load_plays()
    print("collected %d play audits from %d files (brain has %d plays)" % (len(audits), len(files), len(ids)))
    print("\nSUPPORT CLASS:")
    for k, v in Counter(x.get("support_class") for x in audits).most_common():
        print("   %-20s %3d" % (k, v))
    print("\nD24 CORPUS STATE:")
    for k, v in Counter(x.get("d24_state") for x in audits).most_common():
        print("   %-16s %3d" % (k, v))
    print("\nRECOMMENDATION:")
    for k, v in Counter(x.get("recommendation") for x in audits).most_common():
        print("   %-28s %3d" % (k, v))
    ni = sum(len(x.get("instances") or []) for x in audits)
    print("\ninstances traced: %d across %d plays" % (ni, sum(1 for x in audits if x.get("instances"))))
    miss = set(ids) - {x.get("play_id") for x in audits}
    print("plays NOT yet audited: %d %s" % (len(miss), sorted(miss)[:8] if miss else ""))
    if a.out:
        os.makedirs(os.path.dirname(a.out) or ".", exist_ok=True)
        json.dump({"n_plays": len(ids), "audits": audits}, open(a.out, "w", encoding="utf-8"),
                  indent=1, ensure_ascii=False)
        print("\nwrote %s" % a.out)
    return 0


def cmd_fixpaths(a):
    """Rewrite desktop paths in an audit file to repo-relative (D34). Dry-run by default; --write
    backs up first. Re-runnable and idempotent, per S111-3's rule that these tools must survive the
    session that wrote them - a hand edit of 51 citations is exactly what decays."""
    path = a.path
    with open(path, encoding="utf-8") as f:
        raw = f.read()
    d = json.loads(raw)

    changed, unresolved = [], []

    def fix_token(tok):
        t = tok.strip()
        if not _is_machine_path(t):
            return tok, False
        m = re.search(r"(research[/\\]kalshi[/\\].*)", t)
        if not m:
            return tok, False
        new = m.group(1).replace("\\", "/")
        return new, True

    for rec in d.get("audits", []):
        for ins in rec.get("instances", []):
            sf = ins.get("source_file")
            if not sf or not any(_is_machine_path(t) for t in _split_citation(sf)):
                continue
            parts, any_fix = [], False
            for p in _split_citation(sf):
                np_, did = fix_token(p)
                any_fix = any_fix or did
                parts.append(np_)
            new_sf = " + ".join(parts)
            if not any_fix:
                continue
            if not _traces(new_sf):
                unresolved.append((rec["play_id"], sf, new_sf))
            changed.append((rec["play_id"], sf, new_sf))
            if a.write:
                ins["source_file"] = new_sf

    print("%s: %d citations carry a desktop path" % (os.path.relpath(path, ROOT), len(changed)))
    for pid, old, new in changed[:6]:
        print("   %s\n     - %s\n     + %s" % (pid, old[:96], new[:96]))
    if len(changed) > 6:
        print("   ... and %d more" % (len(changed) - 6))
    if unresolved:
        # A rewrite that does not resolve is worse than the original: it looks portable and is not.
        print("\nREFUSED - %d rewritten citations do not resolve; fix by hand:" % len(unresolved))
        for pid, old, new in unresolved:
            print("   %s: %s" % (pid, new[:110]))
        return 1
    if not a.write:
        print("\ndry run - nothing written. Re-run with --write to apply.")
        return 0
    if changed:
        bak = path.replace(".json", "_predesktoppath_backup.json")
        if not os.path.exists(bak):
            with open(bak, "w", encoding="utf-8") as f:
                f.write(raw)
            print("\nbackup: %s" % os.path.relpath(bak, ROOT))
        with open(path, "w", encoding="utf-8") as f:
            json.dump(d, f, indent=1, ensure_ascii=False)
        print("rewrote %d citations in %s" % (len(changed), os.path.relpath(path, ROOT)))
    return 0


def cmd_selftest(a):
    """Every guard must be SHOWN firing on its own defect (D11). Uses a temp file that is deleted
    on exit - nothing is written to the repo and nothing is left outside git (D33)."""
    import tempfile
    _, ids = load_plays()
    b0 = batches(ids)[0]
    good_file = "research/kalshi/knowledge/ng_brain.json"   # tracked, so it resolves

    def inst(path):
        return {"date": "20260701", "group": "g22", "source_file": path,
                "what_the_state_said": "x", "what_the_day_did": "x",
                "supports_or_contradicts": "supports"}

    def rec(pid, insts=None, **over):
        r = {"play_id": pid, "support_class": "ASSERTED", "the_argument": "x",
             "could_evidence_have_come_out_otherwise": "x",
             "d24_state": "found" if insts else "not_searched", "instances": insts or [],
             "condition_can_change_state": "x", "falsifier": "x",
             "recommendation": "keep", "confidence": "low"}
        r.update(over)
        return r

    def doc(audits):
        return {"batch_index": 0, "batch_observations": "x", "audits": audits}

    cases = []
    cases.append(("positive control: well-formed batch validates",
                  doc([rec(p) for p in b0]), None))
    cases.append(("THE TRACEABILITY WALL: fabricated source_file is caught",
                  doc([rec(b0[0], [inst("research/kalshi/forecasts/grp22_C_NEVER_EXISTED.json")])]
                      + [rec(p) for p in b0[1:]]), "does not exist"))
    cases.append(("real source_file still passes (guard is not blanket-rejecting)",
                  doc([rec(b0[0], [inst(good_file)])] + [rec(p) for p in b0[1:]]), None))
    cases.append(("DESKTOP PATH is caught even though the file it names is real",
                  doc([rec(b0[0], [inst("E:/Markets/" + good_file)])] + [rec(p) for p in b0[1:]]),
                  "DESKTOP PATH"))
    cases.append(("multi-file citation joined by + passes when every part resolves",
                  doc([rec(b0[0], [inst(good_file + " + research/kalshi/brain_audit.py")])]
                      + [rec(p) for p in b0[1:]]), None))
    cases.append(("brace list is ONE citation, not split on its commas",
                  doc([rec(b0[0], [inst("renders/ng_refine_s95/g{18,20,22}_actual.json")])]
                      + [rec(p) for p in b0[1:]]), None))
    cases.append(("bare range g17..g23 resolves",
                  doc([rec(b0[0], [inst("renders/ng_refine_s95/g17..g23_actual.json")])]
                      + [rec(p) for p in b0[1:]]), None))
    cases.append(("d24 'searched_none' while listing instances is caught",
                  doc([rec(b0[0], [inst(good_file)], d24_state="searched_none")]
                      + [rec(p) for p in b0[1:]]), "but lists 1 instances"))
    cases.append(("d24 'found' with zero instances is caught",
                  doc([rec(b0[0], d24_state="found")] + [rec(p) for p in b0[1:]]),
                  "lists no instances"))
    other = [p for p in ids if p not in b0][0]
    cases.append(("play borrowed from another batch is caught",
                  doc([rec(p) for p in b0] + [rec(other)]), "not in this batch"))
    cases.append(("dropped play is caught",
                  doc([rec(p) for p in b0[:-1]]), "batch incomplete"))
    cases.append(("invented play id is caught",
                  doc([rec(p) for p in b0] + [rec("weather.invented_play")]), "unknown play_id"))
    cases.append(("missing required field is caught",
                  doc([{k: v for k, v in rec(b0[0]).items() if k != "falsifier"}]
                      + [rec(p) for p in b0[1:]]), "missing falsifier"))
    cases.append(("off-enum support_class is caught",
                  doc([rec(b0[0], support_class="PROBABLY_FINE")] + [rec(p) for p in b0[1:]]),
                  "bad support_class"))

    class _A:
        pass

    ok_all = []
    with tempfile.TemporaryDirectory() as td:
        path = os.path.join(td, "nt.json")
        for name, d, expect in cases:
            json.dump(d, open(path, "w", encoding="utf-8"))
            arg = _A(); arg.path = path
            import io, contextlib
            buf = io.StringIO()
            with contextlib.redirect_stdout(buf):
                rc = cmd_validate(arg)
            out = buf.getvalue()
            if expect is None:
                passed = (rc == 0)
                why = "" if passed else "  (expected clean; got: %s)" % out.strip()[:130]
            else:
                passed = (rc == 1 and expect in out)
                why = "" if passed else "  (guard did not fire; rc=%d out=%s)" % (rc, out.strip()[:130])
            ok_all.append(passed)
            print("  %-4s | %s%s" % ("PASS" if passed else "FAIL", name, why))

    print("\n  %d/%d negative tests passed" % (sum(ok_all), len(ok_all)))
    return 0 if all(ok_all) else 1


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest="cmd", required=True)
    p = sub.add_parser("prompts"); p.add_argument("--batch", type=int, default=None)
    p = sub.add_parser("validate"); p.add_argument("path")
    p = sub.add_parser("collect"); p.add_argument("paths", nargs="+"); p.add_argument("--out")
    sub.add_parser("rubric")
    sub.add_parser("selftest")
    p = sub.add_parser("fixpaths"); p.add_argument("path"); p.add_argument("--write",
                                                                          action="store_true")
    a = ap.parse_args()
    if a.cmd == "prompts":
        return cmd_prompts(a)
    if a.cmd == "validate":
        return cmd_validate(a)
    if a.cmd == "collect":
        return cmd_collect(a)
    if a.cmd == "selftest":
        return cmd_selftest(a)
    if a.cmd == "fixpaths":
        return cmd_fixpaths(a)
    print(RUBRIC)
    return 0


if __name__ == "__main__":
    sys.exit(main())
