#!/usr/bin/env python3
"""
chatgpt_brief_split.py - generate one self-contained hand-off file per task from CHATGPT_BRIEF.

WHY. The brief instructs "one task per conversation", but a single 327-line file makes that awkward:
the recipient has to paste the whole thing and then scroll to the right task, and the model sees five
tasks it was not asked to do. So each task gets its own file carrying the SAME context plus only its
own task.

ONE STORE, GENERATED VIEWS (A-7). The brief is the single source; these files are renders. Editing a
task means editing the brief and re-running this - never editing a split file, which would drift
silently. That is the same principle as brain_audit.py filling prompt slots by lookup, applied to a
document instead of a prompt.

USAGE
    python research/kalshi/chatgpt_brief_split.py          # regenerate all task files
"""

import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
BRIEF = os.path.join(HERE, "CHATGPT_BRIEF_S112.md")
OUT = os.path.join(HERE, "chatgpt_tasks")

HEADER = """# CHATGPT HAND-OFF — TASK {n}: {short}

**This file is self-contained.** Paste the whole thing as your first message. It carries the context
you need and exactly one task. You have no access to our repository, code or data - answer from
public sources. Generated from CHATGPT_BRIEF_S112.md; do not edit this file, edit the brief.

---

"""


def main():
    if not os.path.exists(BRIEF):
        print("brief not found: %s" % os.path.relpath(BRIEF, ROOT))
        return 1
    with open(BRIEF, encoding="utf-8") as f:
        text = f.read()

    # context = everything before the task section; footer = the do-not-bother section
    ctx_end = text.index("## 5. THE TASKS")
    context = text[:ctx_end].rstrip()
    # drop the master file's own "how to use" paragraph - each split file has its own
    context = re.sub(r"\*\*How to use this file\.\*\*.*?(?=\n---)", "", context, flags=re.S).strip()
    # drop the master's H1 - each split file has its own title, and two H1s reads as two documents
    context = re.sub(r"^# [^\n]*\n+", "", context).lstrip("-\n ").lstrip()
    context = "## CONTEXT — the desk, the target, and the rules\n\n" + context
    footer_m = re.search(r"## 6\. WHAT NOT TO SPEND TIME ON.*", text, flags=re.S)
    footer = footer_m.group(0).rstrip() if footer_m else ""

    body = text[ctx_end:]
    parts = re.split(r"\n### (TASK \d+ [^\n]*)\n", body)
    # parts = [pre, title1, chunk1, title2, chunk2, ...]
    made = []
    os.makedirs(OUT, exist_ok=True)
    for i in range(1, len(parts) - 1, 2):
        title, chunk = parts[i].strip(), parts[i + 1]
        chunk = re.sub(r"\n## 6\. WHAT NOT TO SPEND TIME ON.*", "", chunk, flags=re.S)
        chunk = chunk.strip().rstrip("-").rstrip()
        m = re.match(r"TASK (\d+)\s*[-—]+\s*(.*)", title)
        n, short = m.group(1), m.group(2).strip()
        slug = re.sub(r"[^a-z0-9]+", "_", short.lower()).strip("_")[:44]
        # strip a trailing parenthetical from the filename but keep it in the heading
        slug = re.sub(r"_+$", "", slug)
        path = os.path.join(OUT, "TASK_%s_%s.md" % (n, slug))
        with open(path, "w", encoding="utf-8") as f:
            f.write(HEADER.format(n=n, short=short))
            f.write(context)
            f.write("\n\n---\n\n## THE TASK\n\n### " + title + "\n\n" + chunk + "\n\n---\n\n" + footer + "\n")
        made.append(path)
        print("wrote %-64s %5d lines" % (os.path.relpath(path, ROOT),
                                         open(path, encoding="utf-8").read().count("\n")))
    if not made:
        print("no tasks found - check the '### TASK n -' heading format in the brief")
        return 1
    print("\n%d task files generated from %s" % (len(made), os.path.relpath(BRIEF, ROOT)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
