"""Build the self-contained dashboard snapshot pages (desktop + phone) for claude.ai Artifacts.

WHAT THIS MAKES: two single-file HTML pages that embed real store data and run the full
Mission Control UI with NO server - the fetch layer is shimmed to serve embedded JSON.
Published as claude.ai Artifacts they give Greg cruise-able private links; the standing
URLs + refresh procedure live in DASHBOARD_HANDOFF_S100.md (S100.1 addendum).

USAGE (server must be running with the stores pulled - see README.md):
    python -m uvicorn dashboard.server:app --port 8100 &
    python dashboard/make_snapshot.py --out-dir /path/to/scratch [--days 20260122,20260130]

Outputs: davisai-dash-snapshot.html (desktop; viewport width=1130 so a rotated phone
auto-fits it) and davisai-dash-snapshot-phone.html (portrait phone: bottom-tab nav,
single column). Blind-run hygiene: default day list contains NO Feb 2026 days - G12/G13
have not run blind; a guard refuses to embed the un-walked window.
"""
from __future__ import annotations

import argparse
import json
import os
import urllib.request

HERE = os.path.dirname(os.path.abspath(__file__))
FRONTEND = os.path.join(HERE, "frontend")
DEFAULT_DAYS = ["20251223", "20260107", "20260120", "20260122", "20260130", "20260717"]
DEFAULT_TAPE_DAYS = ["20260122"]


def collect_embed(base: str, days: list[str], tape_days: list[str]) -> dict:
    def get(p):
        with urllib.request.urlopen(base + p, timeout=300) as r:
            return json.load(r)

    snapshots = {d: get(f"/desk/snapshot?day={d}") for d in days}
    anchor = snapshots[days[0]]
    shared = {k: anchor[k] for k in ("health", "brain", "lag_map", "doctrine_banner")}
    return {
        "default_day": tape_days[0] if tape_days else days[0],
        "days": days,
        "shared": shared,
        "per_day": {d: {"decision_state": s["decision_state"],
                        "generated_at_utc": s["generated_at_utc"]} for d, s in snapshots.items()},
        "lag_window_atm": get("/lag-map/window?band=ATM"),
        "kalshi_days": get("/kalshi/days"),
        "nymex_bars": {d: get(f"/nymex/minute-bars/{d}") for d in tape_days},
    }


SHIM = """
window.__DAVISAI_EMBED__ = __EMBED_JSON__;
(() => {
  const E = window.__DAVISAI_EMBED__;
  const json = (obj, status = 200) =>
    Promise.resolve(new Response(JSON.stringify(obj), { status, headers: { "Content-Type": "application/json" } }));
  const assemble = day => {
    const pd = E.per_day[day];
    if (!pd) return { as_of_day: day, generated_at_utc: null, ...E.shared,
      decision_state: { available: false, day, error: "day not embedded in this static snapshot - embedded days: " + E.days.join(", ") } };
    return { as_of_day: day, generated_at_utc: pd.generated_at_utc, ...E.shared, decision_state: pd.decision_state };
  };
  const orig = window.fetch.bind(window);
  window.fetch = (url, ...rest) => {
    const u = String(url);
    if (!u.startsWith("/api/v1")) return orig(url, ...rest);
    const [path, qs] = u.slice("/api/v1".length).split("?");
    const params = new URLSearchParams(qs || "");
    if (path === "/desk/snapshot") return json(assemble(params.get("day") || E.default_day));
    if (path === "/lag-map/window") return json(E.lag_window_atm);
    if (path === "/kalshi/days") return json(E.kalshi_days);
    const mBars = path.match(/^\\/nymex\\/minute-bars\\/(\\d{8})$/);
    if (mBars) return json(E.nymex_bars[mBars[1]] ||
      { available: false, day: mBars[1], reason: "tape not embedded in this static snapshot" });
    return json({ available: false, reason: "endpoint not embedded in this static snapshot" }, 404);
  };
})();
"""

# Phone overrides. TRAP NOTES (each cost an iteration): the base css sets
# body{min-width:1180px} (+1120 in its own media query) - the !important zero below is
# load-bearing; body must be the flex column so the banner + shell + bottom nav share the
# viewport; do NOT try CSS zoom to fit - mobile layout-viewport expansion fights it and
# click geometry breaks. The desktop build instead fits rotated phones via
# <meta name="viewport" content="width=1130"> (classic desktop-site scaling, no JS).
PHONE_CSS = """
/* ---------- phone layout (generated by make_snapshot.py) ---------- */
html, body { height: 100%; max-width: 100vw; }
body { display: flex; flex-direction: column; height: 100vh; height: 100dvh; overflow: hidden; min-width: 0 !important; }
body > div:first-child { flex: 0 0 auto; overflow-wrap: anywhere; box-sizing: border-box; }
.app-shell { display: flex; flex-direction: column; flex: 1; min-height: 0; height: auto;
             max-width: 100vw; overflow-x: hidden; }
.main-shell { flex: 1; min-height: 0; height: auto; display: flex; flex-direction: column; overflow-x: hidden; }
.view-container { flex: 1; min-height: 0; overflow: auto; padding: 9px; -webkit-overflow-scrolling: touch; }
.mode-control { flex-wrap: wrap; }
.mode-button { padding: 4px 7px; font-size: 9px; }
.episode-badges { flex-wrap: wrap; }
.chart-toolbar { flex-wrap: wrap; row-gap: 6px; }
.edge-clock-header { flex-wrap: wrap; gap: 4px; }
.edge-marker, .edge-now, .timeline-events { display: none; }
.rail { order: 2; flex-direction: row; align-items: center; border-right: 0;
        border-top: 1px solid var(--border-soft); padding: 4px 6px;
        padding-bottom: calc(4px + env(safe-area-inset-bottom)); }
.brand, .user-badge { display: none; }
.rail-nav { flex-direction: row; flex: 1; gap: 3px; }
.rail-bottom { margin-top: 0; flex-direction: row; }
.nav-item { min-height: 44px; flex: 1; padding: 4px 2px; gap: 2px; }
.nav-label { font-size: 8.5px; }
.topbar { display: flex; flex-wrap: wrap; height: auto; padding: 8px 10px; gap: 8px; row-gap: 6px; }
.topbar h1 { font-size: 15px; }
.environment-pill { font-size: 9px; }
.health-strip { order: 3; width: 100%; overflow-x: auto; padding-bottom: 2px; }
.health-chip { flex: 0 0 auto; }
.topbar-actions { order: 4; width: 100%; flex-wrap: wrap; justify-content: space-between; row-gap: 6px; }
.metric-row { grid-template-columns: 1fr 1fr; }
.mission-grid { grid-template-columns: 1fr; grid-template-areas: "episode" "delta" "coach" "opportunities" "ledger"; }
.episode-layout { grid-template-columns: 1fr; grid-template-areas: "chart" "perception" "stair" "od" "plays" "orders"; }
.weather-grid { grid-template-columns: 1fr; grid-template-areas: "table" "dist" "cycle" "contrib" "cal"; }
.replay-layout { grid-template-columns: 1fr; grid-template-areas: "control" "chart" "snapshot" "requirements" "lineage"; }
.risk-grid, .package-board, .ledger-grid { grid-template-columns: 1fr; }
.coach-call > div, .order-summary > div, .weather-summary-strip > div, .calibration-grid > div { padding: 8px; }
.weather-summary-strip { grid-template-columns: 1fr 1fr; }
.weather-summary-strip > div { border-bottom: 1px solid var(--border-soft); }
.calibration-grid { grid-template-columns: 1fr 1fr; }
.scenario-matrix { grid-template-columns: 74px repeat(4, minmax(52px, 1fr)); overflow-x: auto; }
.live-chart.large { min-height: 190px; }
.asof-json { max-height: 300px; font-size: 10px; }
.delta-row small { word-break: break-word; }
.page-heading { flex-wrap: wrap; gap: 8px; }
.page-actions { flex-wrap: wrap; }
"""


def banner(phone: bool, days: list[str], tape_days: list[str]) -> str:
    tag = "phone build" if phone else "for note-taking"
    day_list = ", ".join(f"{d[4:6]}-{d[6:]}" + (" (default, real NYMEX tape)" if d in tape_days else "")
                         for d in days)
    return f"""
  <div style="background:#1a2438;border-bottom:1px solid rgba(127,224,167,.25);color:#c8d4e8;
              font:{'10' if phone else '12'}px/1.5 ui-monospace,monospace;padding:7px 12px;letter-spacing:.02em">
    STATIC SNAPSHOT ({tag}) - not the live server. Real stores captured at build time.
    Embedded as-of days: {day_list}. Other dates show an honest not-embedded notice.
    Feb 2026 deliberately excluded (blind-run hygiene, G12/G13 not yet walked).
  </div>
"""


def build(embed: dict, phone: bool) -> str:
    html = open(os.path.join(FRONTEND, "index.html")).read()
    css = open(os.path.join(FRONTEND, "styles.css")).read()
    appjs = open(os.path.join(FRONTEND, "app.js")).read()
    adapterjs = open(os.path.join(FRONTEND, "adapter.js")).read()
    body = html.split("<body>", 1)[1].rsplit("</body>", 1)[0]
    body = body.replace('<script src="app.js"></script>', "").replace('<script src="adapter.js"></script>', "")
    viewport = ('<meta name="viewport" content="width=device-width, initial-scale=1.0, viewport-fit=cover" />'
                if phone else '<meta name="viewport" content="width=1130" />')
    title = "DavisAI Mission Control - " + ("phone snapshot" if phone else "snapshot")
    shim = SHIM.replace("__EMBED_JSON__", json.dumps(embed))
    return f"""<title>{title}</title>
{viewport}
<style>{css}
{PHONE_CSS if phone else ''}</style>
{banner(phone, embed['days'], list(embed['nymex_bars']))}
{body}
<script>
{shim}
{appjs}
{adapterjs}
</script>
"""


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--base", default="http://127.0.0.1:8100/api/v1")
    ap.add_argument("--out-dir", required=True)
    ap.add_argument("--days", default=",".join(DEFAULT_DAYS))
    ap.add_argument("--tape-days", default=",".join(DEFAULT_TAPE_DAYS),
                    help="days whose NYMEX minute bars embed (must be local; large)")
    a = ap.parse_args()
    days = a.days.split(",")
    tape_days = [d for d in a.tape_days.split(",") if d]
    feb = [d for d in days + tape_days if d.startswith("202602")]
    if feb:
        raise SystemExit(f"blind-run hygiene: refuse to embed un-walked Feb 2026 days {feb} "
                         "(remove them, or update this guard only after G12/G13 walk)")
    embed = collect_embed(a.base, days, tape_days)
    os.makedirs(a.out_dir, exist_ok=True)
    for phone, name in ((False, "davisai-dash-snapshot.html"), (True, "davisai-dash-snapshot-phone.html")):
        out = os.path.join(a.out_dir, name)
        open(out, "w").write(build(embed, phone))
        print(f"[make_snapshot] {out}: {os.path.getsize(out)/1e6:.2f} MB")
    print("[make_snapshot] publish via the Artifact tool; republishing the same file path from "
          "the SAME conversation keeps the URL - from a new session pass the existing artifact "
          "URL (see the S100.1 addendum in DASHBOARD_HANDOFF_S100.md)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
